spring:
  application:
    name: ms-discovery
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
server:
  port: ${SERVER_PORT:8763}

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 1000
    renewal-percent-threshold: 0.49
  client:
    fetch-registry: false
    register-with-eureka: false

