spring:
  application:
    name: ms-discovery
server:
  port: 8763

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 1000
    renewal-percent-threshold: 0.49
  client:
    fetch-registry: false
    register-with-eureka: false

